services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    ports:
      - "3000:3000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
      - "4004:4004"
    env_file:
      - .env
    depends_on:
      - register
      - login
      - main
      - card

  register:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: register-service
    env_file:
      - .env

  login:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: login-service
    env_file:
      - .env

  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: main-service
    env_file:
      - .env

  card:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: card-service
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:3001"
    environment:
      - VITE_API_BASE_URL=http://backend:3000
